//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181008.1&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;Sastasha&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;Brayflox&apos;s Longstop&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;The Wanderer&apos;s Palace&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;Copperbell Mine [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data_EN_US {
            get {
                return ResourceManager.GetString("Data_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181008.1&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;Sastasha&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;le Bivouac de Brayflox&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;le Palais du Vagabond&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;les Mines de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data_FR_FR {
            get {
                return ResourceManager.GetString("Data_FR_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181008.1&quot;, 
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;天然要害 サスタシャ浸食洞&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;奪還支援 ブレイフロクスの野営地&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;旅神聖域 ワンダラーパレス&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;封鎖坑道 カッパーベル銅山&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data_JA_JP {
            get {
                return ResourceManager.GetString("Data_JA_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  // 버전
        ///  &quot;version&quot;: &quot;20181008.1&quot;,
        ///
        ///  // 임무
        ///  &quot;instances&quot;: {
        ///    // 2.0 신생 에오르제아
        ///    // 2.0 던전
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;사스타샤 침식 동굴&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;브레이플록스의 야영지&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;방랑자의 궁전&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;구리종 광산&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data_KO_KR {
            get {
                return ResourceManager.GetString("Data_KO_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  // Version
        ///  &quot;version&quot;: &quot;20181008.1&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;Sastasha&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;Brayflox&apos;s Longstop&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;The Wanderer&apos;s Palace&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;Copperbell Mine [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data_ZH_CN {
            get {
                return ResourceManager.GetString("Data_ZH_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap language2 {
            get {
                object obj = ResourceManager.GetObject("language2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;app-name&quot;: &quot;Duty/FATE Notificator&quot;,
        ///
        ///
        ///  &quot;unknown-instance&quot;: &quot;Unknown Duty ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;Unknown Roulette ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;Unknown Area ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;Unknown FATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;Version {0} Updated&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; Matched!&quot;,
        ///  &quot;notification-fate-occured&quot;: &quot;&lt; {0} &gt; Occured!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; FATE Occured!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; Matched!&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localization_EN_US {
            get {
                return ResourceManager.GetString("Localization_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;app-name&quot;: &quot;Notificateur Mission/ALEA&quot;,
        ///
        ///
        ///  &quot;unknown-instance&quot;: &quot;Mission inconnue ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;Mission aléatoire inconnue ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;Zone inconnue ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;ALEA inconnu ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;Mise à jour version {0}&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; disponible!&quot;,
        ///  &quot;notification-fate-occured&quot;: &quot;&lt; {0} &gt; en cours!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;ALEA &lt; {0} &gt; en cours!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; disponible [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localization_FR_FR {
            get {
                return ResourceManager.GetString("Localization_FR_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;app-name&quot;: &quot;Duty/FATE Notificator&quot;,
        ///
        ///
        ///  &quot;unknown-instance&quot;: &quot;不明なコンテンツ ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;不明なルーレット ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;不明なエリア ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;不明なFATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;バージョン {0} に更新されました&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 突入準備完了!&quot;,
        ///  &quot;notification-fate-occured&quot;: &quot;&lt; {0} &gt; 発生!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; FATE発生!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; 突入準備完了!&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;炎天一巻&quot;,
        ///  &quot;fate-preset-an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localization_JA_JP {
            get {
                return ResourceManager.GetString("Localization_JA_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;app-name&quot;: &quot;임무/돌발 찾기 도우미&quot;,
        ///
        ///
        ///  &quot;unknown-instance&quot;: &quot;알 수 없는 임무 ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;알 수 없는 무작위 임무 ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;알 수 없는 지역 ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;알 수 없는 돌발 ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;버전 {0} 업데이트됨&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 매칭!&quot;,
        ///  &quot;notification-fate-occured&quot;: &quot;&lt; {0} &gt; 발생!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; 돌발 발생!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; 매칭!&quot;,
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;불의 서 1권&quot;,
        ///  &quot;fate-preset-animus-Skyfire [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localization_KO_KR {
            get {
                return ResourceManager.GetString("Localization_KO_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;app-name&quot;: &quot;Duty/FATE Assist&quot;,
        ///
        ///
        ///  &quot;unknown-instance&quot;: &quot;未知副本 ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;未知随机副本 ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;未知区域 ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;未知FATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;升级版本{0}&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 已匹配!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; FATE 出现!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; Duty 已匹配!&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;Book of Skyfire I&quot;,
        ///  &quot;fate-preset-animus-SkyfireII&quot;: &quot;Book of Skyfire II&quot;,
        ///  &quot;fate-preset-anim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localization_ZH_CN {
            get {
                return ResourceManager.GetString("Localization_ZH_CN", resourceCulture);
            }
        }
    }
}
